# Generated by Django 2.1 on 2018-08-29 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('Act_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Content', models.TextField()),
                ('BMStartTime', models.DateTimeField()),
                ('BMEndTime', models.DateTimeField()),
                ('CTStartTime', models.DateTimeField()),
                ('CTEndTime', models.DateTimeField()),
                ('Kind', models.CharField(max_length=15)),
                ('Level', models.CharField(max_length=15)),
                ('Holder', models.CharField(max_length=30)),
                ('Allower', models.CharField(max_length=30)),
                ('Tag', models.TextField()),
                ('ReleaseTime', models.DateTimeField(auto_now_add=True)),
                ('LastChangeTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=20)),
                ('PassWord', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
                ('LastChangeTime', models.DateTimeField(auto_now=True)),
                ('Tag', models.TextField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubAdmin',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Student')),
                ('Club', models.CharField(max_length=30)),
            ],
            bases=('app.student',),
        ),
    ]
